# Generated by Django 3.0.8 on 2020-07-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField(max_length=10)),
                ('release_Date', models.DateField()),
                ('duration', models.FloatField(max_length=10)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
