# Generated by Django 3.0.8 on 2020-07-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_apis', '0002_auto_20200726_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.TimeField(),
        ),
    ]
