# Generated by Django 3.0.8 on 2020-07-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_apis', '0003_auto_20200726_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(max_length=25),
        ),
    ]
