# Generated by Django 3.0.8 on 2020-07-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_apis', '0005_auto_20200726_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.CharField(max_length=25),
        ),
    ]
