# Generated by Django 3.0.8 on 2020-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_apis', '0006_auto_20200727_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
